sudo: false
language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "nightly"

before_install:
   - pip install pytest-cov
   - pip install coveralls

install: "pip install -r requirements.txt"

script: py.test --cov striplog tests

after_success:
   - coveralls
